service: twitter-lambda
frameworkVersion: '3'

package:
  individually: true
  artifact: build.zip

provider:
  name: aws
  runtime: python3.7
  stage: ${env:MY_ENV}
  region: ${env:MY_REGION}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:*
            - dynamodb:*
          Resource: "*"

functions:
  hello:
    handler: handler.hello
    events: 
      - schedule:
          rate: cron(30 16 * * ? *)
          name: python-send-question
          description: "send python question daily at 2pm utc or 9am us time"
          input:
            language: python
      - schedule:
          rate: cron(30 12 * * ? *)
          name: r-send-question
          description: "send r question daily at 3am utc or 10pm us time or 8:30 am ist"
          input:
            language: r
      - schedule: cron(30 12 * * ? *)
      - 

    maximumRetryAttempts: 1
    memorySize: 512
    timeout: 60
    environment: 
      TWITTER_API_SECRET: ${env:TWITTER_API_SECRET}
      TWITTER_API_KEY: ${env:TWITTER_API_KEY}
      TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
      MY_ENV: ${env:MY_ENV}
      MY_REGION: ${env:MY_REGION}